#!/usr/bin/env python3
# download MIT KEMAR HRTF dataset (SOFA format) and convert to a C header
# containing FFT'd impulse responses for use in the frequency-domain spatializer
#
# output: hrtf_data.h with HRIR data at measured positions
#
# the KEMAR dataset has measurements at:
#   - 710 positions (azimuth/elevation pairs)
#   - 128 samples per impulse response at 44100Hz
#   - left and right ear

import os, sys, struct
import numpy as np
import h5py
import urllib.request

KEMAR_URL = "https://sofacoustics.org/data/database/mit/mit_kemar_normal_pinna.sofa"
SOFA_PATH = "kemar.sofa"
OUTPUT = "hrtf_data.h"

# we'll store HRTFs at a grid of positions and interpolate at runtime
# keep a subset for reasonable binary size
TARGET_ELEVATIONS = [-40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
AZ_STEP = 5  # degrees between azimuth measurements to keep

def download():
    if os.path.exists(SOFA_PATH):
        print(f'  {SOFA_PATH} already exists')
        return
    print(f'  downloading KEMAR SOFA file...')
    urllib.request.urlretrieve(KEMAR_URL, SOFA_PATH)
    print(f'  done ({os.path.getsize(SOFA_PATH) / 1e6:.1f}MB)')

def load_sofa():
    f = h5py.File(SOFA_PATH, 'r')
    # SOFA format: positions in (M, 3) as [azimuth, elevation, distance]
    positions = f['SourcePosition'][:]  # (M, 3)
    irs = f['Data.IR'][:]               # (M, 2, N) — 2 ears, N samples
    sr = f['Data.SamplingRate'][0]
    print(f'  {len(positions)} measurements, {irs.shape[2]} samples, {int(sr)}Hz')
    return positions, irs, int(sr)

def select_positions(positions, irs):
    """keep a useful subset of positions for reasonable size"""
    selected_pos = []
    selected_irs = []

    for i, (az, el, dist) in enumerate(positions):
        # find closest target elevation
        el_rounded = min(TARGET_ELEVATIONS, key=lambda e: abs(e - el))
        if abs(el - el_rounded) > 2.5:
            continue

        # keep every AZ_STEP degrees of azimuth
        az_mod = az % 360
        if az_mod > 180:
            az_mod -= 360
        if abs(az_mod) % AZ_STEP > 1:
            continue

        selected_pos.append((az_mod, el_rounded))
        selected_irs.append(irs[i])

    # deduplicate (take first occurrence)
    seen = set()
    unique_pos = []
    unique_irs = []
    for pos, ir in zip(selected_pos, selected_irs):
        key = (round(pos[0]), round(pos[1]))
        if key not in seen:
            seen.add(key)
            unique_pos.append(key)
            unique_irs.append(ir)

    print(f'  selected {len(unique_pos)} positions')
    return unique_pos, np.array(unique_irs)

def generate_header(positions, irs, sr):
    """generate C header with HRIR data"""
    n_pos = len(positions)
    n_samples = irs.shape[2]

    # FFT the IRs for frequency-domain convolution
    # fft_size must be >= block_size + ir_length - 1 to avoid circular convolution
    # block_size=512, ir_length=512 -> need 1023 -> round to 1024
    fft_size = 1024
    hrtfs = np.fft.rfft(irs, n=fft_size, axis=2)  # (M, 2, fft_size//2+1) complex
    n_bins = fft_size // 2 + 1

    with open(OUTPUT, 'w') as f:
        f.write("/* KEMAR HRTF data — auto-generated by fetch_kemar.py */\n")
        f.write("/* MIT KEMAR normal pinna, measured at 44100Hz */\n")
        f.write("/* DO NOT EDIT — regenerate with: python3 fetch_kemar.py */\n\n")
        f.write(f"#define HRTF_N_POSITIONS {n_pos}\n")
        f.write(f"#define HRTF_FFT_SIZE {fft_size}\n")
        f.write(f"#define HRTF_N_BINS {n_bins}\n")
        f.write(f"#define HRTF_SAMPLE_RATE {sr}\n")
        f.write(f"#define HRTF_IR_LEN {n_samples}\n\n")

        # positions array: azimuth, elevation in degrees
        f.write("static const float hrtf_positions[][2] = {\n")
        for az, el in positions:
            f.write(f"\t{{ {az:.1f}f, {el:.1f}f }},\n")
        f.write("};\n\n")

        # HRTF data: real and imag parts interleaved for each ear
        # layout: [position][ear][bin] where each bin is {real, imag}
        f.write("static const float hrtf_data[][2][HRTF_N_BINS * 2] = {\n")
        for i in range(n_pos):
            f.write("\t{\n")
            for ear in range(2):
                f.write("\t\t{ ")
                vals = []
                for b in range(n_bins):
                    vals.append(f"{hrtfs[i, ear, b].real:.6f}f")
                    vals.append(f"{hrtfs[i, ear, b].imag:.6f}f")
                f.write(", ".join(vals))
                f.write(" },\n")
            f.write("\t},\n")
        f.write("};\n")

    size_kb = os.path.getsize(OUTPUT) / 1024
    print(f'  wrote {OUTPUT} ({size_kb:.0f}KB, {n_pos} positions, {n_bins} bins)')

def main():
    download()
    positions, irs, sr = load_sofa()
    sel_pos, sel_irs = select_positions(positions, irs)
    generate_header(sel_pos, sel_irs, sr)
    print(f'  done. include hrtf_data.h in your spatializer')

if __name__ == '__main__':
    os.makedirs(os.path.dirname(os.path.abspath(__file__)) or '.', exist_ok=True)
    os.chdir(os.path.dirname(os.path.abspath(__file__)) or '.')
    main()
